"""add audit new fields facebook column

Revision ID: 4e05167632da
Revises: 
Create Date: 2026-08-20 17:38:40.234044
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4e05167632da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_title_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meta_desc_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_viewport', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_blog_content', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('blog_freshness_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instagram_exists', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('instagram_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('instagram_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('facebook_exists', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('facebook_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('google_business_complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_catalog_link', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_responds_badge', sa.Boolean(), nullable=True))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook', sa.String(length=200), nullable=True))

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.alter_column('audit_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.alter_column('audit_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('facebook')

    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_responds_badge')
        batch_op.drop_column('whatsapp_catalog_link')
        batch_op.drop_column('google_business_complete')
        batch_op.drop_column('facebook_active')
        batch_op.drop_column('facebook_exists')
        batch_op.drop_column('instagram_active')
        batch_op.drop_column('instagram_public')
        batch_op.drop_column('instagram_exists')
        batch_op.drop_column('blog_freshness_days')
        batch_op.drop_column('has_blog_content')
        batch_op.drop_column('has_viewport')
        batch_op.drop_column('meta_desc_length')
        batch_op.drop_column('meta_title_length')

    # ### end Alembic commands ###
