"""add message send_attempts last_error

Revision ID: c5254553fe9a
Revises: 4e05167632da
Create Date: 2026-08-20 19:13:33.626469
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c5254553fe9a'
down_revision: Union[str, None] = '4e05167632da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('last_error')
        batch_op.drop_column('send_attempts')

    # ### end Alembic commands ###
